-- Combined PostgreSQL Initialization Script
-- Generated by infra/postgres/generateinitscript.js
-- Generated at: 2026-03-06T20:03:26.307Z

-- ============================================
-- Source: 01-extensions.sql
-- ============================================

-- 1. Enable Extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Verify extensions
SELECT * FROM pg_extension WHERE extname IN ('vector', 'pgcrypto', 'uuid-ossp');


-- ============================================
-- Source: 02-permissions.sql
-- ============================================
-- 2. Create Application User
DO
$$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'spring_user') THEN
    CREATE USER spring_user WITH PASSWORD 'spring_password';
END IF;
END
$$;

-- 3. Grant Permissions
-- Ensure the application user has full access to the database and public schema
GRANT ALL PRIVILEGES ON DATABASE spring_creator TO spring_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO spring_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO spring_user;


