version: '3'

dotenv: ['.env']

tasks:
  build:
    desc: Build fat jar
    cmds:
      - ./gradlew clean build -x test

  dev:
    desc: Run Spring Boot with fast startup and auto-restart
    cmds:
      - ./gradlew bootRun --continuous

  test:
    desc: Run HTTP tests
    cmds:
      - ijhttp --env-file requests/http-client.env.json --env dev requests/session7/mcpclient.http

  clean-gradle:
    desc: Stop all Gradle daemons and clean cache
    cmds:
      - ./gradlew --stop
      - echo "All Gradle daemons stopped."
