#!/usr/bin/env bun

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Load environment variables (Bun automatically loads .env if present, 
// but we can also fallback to defaults)
const POSTGRES_DB = process.env.POSTGRES_DB || 'spring_creator';
const POSTGRES_USER = process.env.POSTGRES_USER || 'spring_user';

// Read all SQL template files from the sql directory
const sqlDir = join(import.meta.dir, 'sql');
const sqlFiles = readdirSync(sqlDir)
  .filter(file => file.endsWith('.sql'))
  .sort(); // This will sort them as 01, 02, 03, etc.

console.log(`📂 Found ${sqlFiles.length} SQL template files:`);
sqlFiles.forEach(file => console.log(`   - ${file}`));

// Combine all SQL files
let combinedSql = `-- Combined PostgreSQL Initialization Script
-- Generated by infra/postgres/generateinitscript.js
-- Generated at: ${new Date().toISOString()}

`;

for (const file of sqlFiles) {
  const filePath = join(sqlDir, file);
  let content = readFileSync(filePath, 'utf-8');
  
  // Replace template variables
  content = content
    .replace(/\{\{POSTGRES_DB\}\}/g, POSTGRES_DB)
    .replace(/\{\{POSTGRES_USER\}\}/g, POSTGRES_USER);
  
  combinedSql += `-- ============================================\n`;
  combinedSql += `-- Source: ${file}\n`;
  combinedSql += `-- ============================================\n\n`;
  combinedSql += content;
  combinedSql += `\n\n`;
}

// Write the combined SQL file
//infra/postgres/initdb
const outputPath = join(import.meta.dir,'initdb', 'init-db.sql');
writeFileSync(outputPath, combinedSql);

console.log(`\n✅ Successfully generated ${outputPath}`);
console.log(`📦 Target Database: ${POSTGRES_DB}`);
console.log(`👤 Target User: ${POSTGRES_USER}`);
console.log(`\n🚀 You can now run this script against your database:`);
console.log(`\npsql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f ${outputPath}`);
console.log(combinedSql)